baseURL       = "https://aish-where-ya.github.io/Portfolio/"
languageCode  = "en-us"
title         = "Aishwarya Harpale | Portfolio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Hello, I'm Aishwarya Harpale. And I code!"
    tagline               = "WELCOME TO MY PAGE"
    primary_button        = "See My Work"
    primary_button_url    = "portfolio"
    secondary_button      = "View Resume"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LETâ€™S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      email   = "aishwaryaharpale14@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Github"
          url  = "#"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"